linters-settings:
  unused:
    check-exported: false

linters:
  disable-all: true
  enable:
    - govet
    - unused
    - errcheck
    - staticcheck

issues:
  exclude-dirs:
    - vendor
    - testdata